import { Project, Member } from './types';

export const MOCK_MEMBERS: Member[] = [
  { id: 'm1', name: '이광수', team: '마케팅사업부문' },
  { id: 'm2', name: '김혜진(크리랩)', team: 'Creative.Lab' },
  { id: 'm3', name: '손소리', team: 'R&D' },
  { id: 'm4', name: '임동욱', team: 'AI Tech Lab' },
  { id: 'm5', name: '왕선영', team: '마케팅4팀' },
  { id: 'm6', name: '최경영', team: '마케팅1팀' },
  { id: 'm7', name: '김선우', team: 'CC' },
  { id: 'm8', name: '전지영', team: 'PM실 플랫폼팀' },
  { id: 'm9', name: '김보민', team: '마케팅4팀' },
  { id: 'm10', name: '박화진', team: '마케팅6팀' },
  { id: 'm11', name: '김보미', team: '마케팅4팀' },
  { id: 'm12', name: '조일환', team: '마케팅2팀' },
  { id: 'm13', name: '이광복', team: 'Creative.Lab' },
  { id: 'm14', name: '김익현', team: '마케팅2팀' },
  { id: 'm15', name: '천성화', team: '마케팅4팀' },
  { id: 'm16', name: '김영현', team: '마케팅5팀' },
  { id: 'm17', name: '문영란', team: 'AI Tech Lab' },
  { id: 'm18', name: '조혜진', team: 'AI Tech Lab' },
  { id: 'm19', name: '이선희', team: 'Creative.Lab' },
  { id: 'm20', name: '조원형', team: '마케팅6팀' },
  { id: 'm21', name: '박승혁', team: '마케팅3팀' },
  { id: 'm22', name: '최신해', team: '세일즈TFT' },
  { id: 'm23', name: '남훈경', team: '마케팅1팀' },
  { id: 'm24', name: '김우진', team: 'Creative.Lab' },
  { id: 'm25', name: '이채영', team: '마케팅2팀' },
  { id: 'm26', name: '정유진', team: '마케팅5팀' },
  { id: 'm27', name: '최원태', team: 'R&D' },
  { id: 'm28', name: '윤혜진', team: 'PM실 PM팀' },
  { id: 'm29', name: '김수진(R&D)', team: 'R&D' },
  { id: 'm30', name: '조현호', team: 'AI Tech Lab' },
  { id: 'm31', name: '김정태', team: '마케팅2팀' },
  { id: 'm32', name: '정지성', team: '마케팅1팀' },
  { id: 'm33', name: '조민주', team: 'PM실 PM팀' },
  { id: 'm34', name: '권현호', team: '세일즈TFT' },
  { id: 'm35', name: '김민선', team: 'PM실 PM팀' },
  { id: 'm36', name: '한세희', team: 'PM실 PM팀' },
  { id: 'm37', name: '문성희', team: 'Creative.Lab' },
  { id: 'm38', name: '조연수', team: '마케팅1팀' },
  { id: 'm39', name: '이지원', team: '마케팅1팀' },
  { id: 'm40', name: '신희도', team: 'CC' },
  { id: 'm41', name: '류승일', team: '마케팅2팀' },
  { id: 'm42', name: '윤희진', team: '마케팅6팀' },
  { id: 'm43', name: '김태남', team: '마케팅4팀' },
  { id: 'm44', name: '김남솔', team: '마케팅3팀' },
  { id: 'm45', name: '박민규', team: '마케팅1팀' },
  { id: 'm46', name: '김지연(R&D)', team: 'R&D' },
  { id: 'm47', name: '이용희', team: '세일즈TFT' },
  { id: 'm48', name: '정수아', team: '마케팅1팀' },
  { id: 'm49', name: '이정진', team: 'Creative.Lab' },
  { id: 'm50', name: '이창환', team: '마케팅3팀' },
  { id: 'm51', name: '정성은', team: '마케팅3팀' },
  { id: 'm52', name: '김세형', team: '마케팅6팀' },
  { id: 'm53', name: '임성열', team: '마케팅2팀' },
  { id: 'm54', name: '이수민', team: 'PM실 PM팀' },
  { id: 'm55', name: '강수빈', team: '마케팅2팀' },
  { id: 'm56', name: '김민국', team: '마케팅5팀' },
  { id: 'm57', name: '구본혁', team: 'Creative.Lab' },
  { id: 'm58', name: '박선민', team: 'PM실' },
  { id: 'm59', name: '강유진', team: 'PM실 PM팀' },
  { id: 'm60', name: '김남주', team: 'PM실 PM팀' },
  { id: 'm61', name: '전다예', team: '마케팅3팀' },
  { id: 'm62', name: '김아원', team: '마케팅6팀' },
  { id: 'm63', name: '김민주', team: 'PM실 PM팀' },
  { id: 'm64', name: '서윤희', team: 'Creative.Lab' },
  { id: 'm65', name: '정문영', team: 'Creative.Lab' },
  { id: 'm66', name: '김민하', team: '마케팅1팀' },
  { id: 'm67', name: '김상욱', team: '마케팅2팀' },
  { id: 'm68', name: '장세훈', team: '마케팅3팀' },
  { id: 'm69', name: '오정은', team: 'AI Tech Lab' },
  { id: 'm70', name: '정대욱', team: '마케팅6팀' },
  { id: 'm71', name: '이시은(4T)', team: '마케팅2팀' },
  { id: 'm72', name: '김보현', team: '마케팅4팀' },
  { id: 'm73', name: '김민지', team: '마케팅6팀' },
  { id: 'm74', name: '차은채', team: 'PM실 PM팀' },
  { id: 'm75', name: '김준하', team: '세일즈TFT' },
  { id: 'm76', name: '강유찬', team: '마케팅1팀' },
  { id: 'm77', name: '이한결', team: '마케팅6팀' },
  { id: 'm78', name: '장지수', team: '마케팅1팀' },
  { id: 'm79', name: '국정현', team: '마케팅3팀' },
  { id: 'm80', name: '김수연', team: '마케팅5팀' },
  { id: 'm81', name: '박예슬', team: '마케팅1팀' },
  { id: 'm82', name: '백호정', team: '마케팅1팀' },
  { id: 'm83', name: '이동제', team: '마케팅4팀' },
  { id: 'm84', name: '정의창', team: '마케팅3팀' },
  { id: 'm85', name: '최재언', team: '마케팅6팀' },
  { id: 'm86', name: '정수빈', team: 'AI Tech Lab' },
  { id: 'm87', name: '정원형', team: 'AI Tech Lab' },
  { id: 'm88', name: '장인영', team: 'Creative.Lab' },
  { id: 'm89', name: '장재현', team: '미지정' },
  { id: 'm90', name: '이지은', team: 'PM실 PM팀' },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'PROPJ00001',
    campaignName: 'ibk기업은행(나라사랑 카드)',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/19EysBeTxwPmbvKclMgsMUHF-mPb9izk4HUAo96ucCAc/edit?usp=drive_link',
    rValue: 600000000,
    commission: 0.15,
    team: '마케팅4팀',
    pl: '',
    submittedAt: '2025-06-16',
    year: 2025,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 1800000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '[수주실패] 미지급',
    members: [],
  },
  {
    id: 'PROPJ00002',
    campaignName: 'P&G_G&O',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1wJLxwMtANr36F9QvN8kzEcatnasq8quip004EtkvFUQ/edit?usp=drive_link',
    rValue: 9832294826,
    commission: 0.0,
    team: '마케팅2팀',
    pl: '최경영',
    submittedAt: '2025-01-01',
    year: 2025,
    status: 'SECOND_PENDING',
    incentiveRate: 2,
    incentiveFund: 12332940,
    firstPaymentDate: '2025-08-08',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2026-08-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '계약기간 :  2025. 07. 01 ~ 2026. 06. 30 250704 8/8(금) 1차지급(Braun, Gillette, Oral-B 각각 지급)',
    members: [
      { memberId: 'm6', memberName: '최경영', contribution: 25 },
      { memberId: 'unknown', memberName: '손유찬', contribution: 10 },
      { memberId: 'unknown', memberName: '이해성', contribution: 15 },
      { memberId: 'unknown', memberName: '정소미', contribution: 5 },
      { memberId: 'm23', memberName: '남훈경', contribution: 15 },
      { memberId: 'unknown', memberName: '최병일', contribution: 5 },
      { memberId: 'm48', memberName: '정수아', contribution: 0 },
      { memberId: 'm32', memberName: '정지성', contribution: 15 },
      { memberId: 'm38', memberName: '조연수', contribution: 5 },
      { memberId: 'm39', memberName: '이지원', contribution: 5 }
    ],
  },
  {
    id: 'PROPJ00003',
    campaignName: 'F&F',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1Hs4ilNkDci8xPqa67rT0avGOANChfkTbGAUBfYa_RYI/edit?usp=drive_link',
    rValue: 8500000000,
    commission: 0.1,
    team: '마케팅1팀',
    pl: '',
    submittedAt: '2025-06-27',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 17000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00004',
    campaignName: '코코지',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1XFzvECKSHLH5lJTdkeDkCa8vUp67tXsUFj_4Opbd0lI/edit?usp=drive_link',
    rValue: 1500000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '',
    submittedAt: '2025-03-28',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 3000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00005',
    campaignName: '경민대',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1lC52Npmo_EsxvsRBal6M_ihpmdwKQxbbBZj9nY9iX0o/edit?usp=drive_link',
    rValue: 600000000,
    commission: 0.123,
    team: '마케팅4팀',
    pl: '',
    submittedAt: '2025-07-04',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 1476000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00006',
    campaignName: '설로인',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/17sqEffPM9dMQwlAc3hMN1EDzbv6lb6wuNjMdgh873OU/edit?usp=drive_link',
    rValue: 1080000000,
    commission: 0.08,
    team: '마케팅4팀',
    pl: '김익현',
    submittedAt: '2025-06-03',
    year: 2025,
    status: 'ALL_PAID',
    incentiveRate: 2,
    incentiveFund: 1728000,
    firstPaymentDate: '2025-08-08',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2026-02-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: true,
    slackNotified: true,
    note: '2026. 02. 10 2차 수주인센티브 지급 계약기간 2025. 12. 31까지 250704 1차 지급액 정상지급 (8/8 지급진행)',
    members: [
      { memberId: 'm14', memberName: '김익현', contribution: 50 },
      { memberId: 'm41', memberName: '류승일', contribution: 50 }
    ],
  },
  {
    id: 'PROPJ00007',
    campaignName: '데싱디바',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1oisUMoOdM7UBgUpZV-RrkPGyBKrUypb1Shr9rngCexs/edit?usp=drive_link',
    rValue: 750000000,
    commission: 0.15,
    team: '마케팅4팀',
    pl: '김익현',
    submittedAt: '2025-06-04',
    year: 2025,
    status: 'SECOND_PENDING',
    incentiveRate: 2,
    incentiveFund: 2250000,
    firstPaymentDate: '2025-08-08',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2026-07-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '계약기간 2025. 05. 31까지 250704 1차 지급액 정상지급 (8/8 지급진행)',
    members: [
      { memberId: 'm14', memberName: '김익현', contribution: 40 },
      { memberId: 'm31', memberName: '김정태', contribution: 30 },
      { memberId: 'm25', memberName: '이채영', contribution: 30 }
    ],
  },
  {
    id: 'PROPJ00008',
    campaignName: '아마메르',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1DOa9Bj1r6nh2CQJTcyHb0szFv81V4JiCsxZ0ftLloQA/edit?usp=drive_link',
    rValue: 1200000000,
    commission: 0.15,
    team: '마케팅4팀',
    pl: '김익현',
    submittedAt: '2025-01-01',
    year: 2025,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 3600000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '[대행종료] 250704 1~2개월 소진액 트래킹 후 1차 지급 진행  [대행종료]',
    members: [],
  },
  {
    id: 'PROPJ00009',
    campaignName: 'KB핀테크',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1r-8_b79pvd_fA7R4ynQ57D3hDWGmWdjNBuIIg3FQLts/edit?usp=drive_link',
    rValue: 1920000000,
    commission: 0.1,
    team: '마케팅1팀',
    pl: '정소미',
    submittedAt: '2025-04-04',
    year: 2025,
    status: 'FIRST_PAID',
    incentiveRate: 2,
    incentiveFund: 3840000,
    firstPaymentDate: '2025-07-10',
    firstPaymentRatio: 40,
    secondPaymentRatio: 0,
    secondPaymentDate: undefined,
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '계약기간 2026. 04. 14 까지 250710 1차 지급 완료',
    members: [
      { memberId: 'unknown', memberName: '정소미', contribution: 25 },
      { memberId: 'm9', memberName: '김보민', contribution: 20 },
      { memberId: 'm11', memberName: '김보미', contribution: 20 },
      { memberId: 'm42', memberName: '윤희진', contribution: 20 },
      { memberId: 'unknown', memberName: 'Creative.Lab', contribution: 10 },
      { memberId: 'unknown', memberName: '최봉준', contribution: 5 }
    ],
  },
  {
    id: 'PROPJ00010',
    campaignName: '유니세프',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1-3SSIqMvHsGj1Bb05X5h1n2YA-IU1TtienWm9k11nZk/edit?gid=1999174495#gid=1999174495',
    rValue: 1700000000,
    commission: 0.1,
    team: '마케팅1팀',
    pl: '박화진',
    submittedAt: '2025-07-17',
    year: 2025,
    status: 'ALL_PAID',
    incentiveRate: 2,
    incentiveFund: 3400000,
    firstPaymentDate: '2025-07-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2026-05-08',
    firstPaymentCompleted: true,
    secondPaymentCompleted: true,
    slackNotified: true,
    note: '계약기간: 2026. 03. 31 까지 (2025. 12. 31에서 연장됨) 250710 1차 지급 완료',
    members: [
      { memberId: 'm10', memberName: '박화진', contribution: 55 },
      { memberId: 'unknown', memberName: '김혜리', contribution: 30 },
      { memberId: 'unknown', memberName: 'Creative.Lab', contribution: 15 }
    ],
  },
  {
    id: 'PROPJ00011',
    campaignName: 'NH투자증권(나무증권)',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1mzg8aSSgducKA0bqe6OOMbrpNkyQCBscWkDLkcY0nvE/edit?gid=255264786#gid=255264786',
    rValue: 5000000000,
    commission: 0.13,
    team: '마케팅1팀',
    pl: '정소미',
    submittedAt: '2024-12-20',
    year: 2024,
    status: 'ALL_PAID',
    incentiveRate: 2,
    incentiveFund: 13000000,
    firstPaymentDate: '2025-02-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2026-02-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: true,
    slackNotified: true,
    note: '2026. 02. 10 2차 수주인센티브 지급 계약기간 2025. 12. 31 까지 250210 1차 지급 완료',
    members: [
      { memberId: 'unknown', memberName: '정소미', contribution: 40 },
      { memberId: 'unknown', memberName: '송두리', contribution: 25 },
      { memberId: 'm20', memberName: '조원형', contribution: 25 },
      { memberId: 'unknown', memberName: 'Creative.Lab', contribution: 10 },
      { memberId: 'unknown', memberName: 'Creative. Lab', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00012',
    campaignName: 'DB손해보험(장기보험TM)',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1HPR7jLwVF9HOQRh2s6xcnO5PAYasTliuRRUJ5hXzZM0/edit?gid=1311711477#gid=1311711477',
    rValue: 6700000000,
    commission: 0.0,
    team: '마케팅5팀',
    pl: '김영현',
    submittedAt: '2024-11-08',
    year: 2024,
    status: 'ALL_PAID',
    incentiveRate: 2,
    incentiveFund: 7700000,
    firstPaymentDate: '2025-02-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2026-02-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: true,
    slackNotified: true,
    note: '2026. 02. 10 2차 수주인센티브 지급 계약기간 2025. 12. 31 까지 250110 1차 지급 완료',
    members: [
      { memberId: 'm16', memberName: '김영현', contribution: 50 },
      { memberId: 'm26', memberName: '정유진', contribution: 25 },
      { memberId: 'm34', memberName: '권현호', contribution: 5 },
      { memberId: 'unknown', memberName: '김규리', contribution: 10 },
      { memberId: 'unknown', memberName: 'Creative.Lab', contribution: 10 },
      { memberId: 'unknown', memberName: 'Creative. Lab', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00013',
    campaignName: 'CyberZ(DMM게임즈)',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1xohM7oZyqT_PR25nTV-W9Y6xQk0R9DovSMBaYLc3TFQ/edit?gid=1430583426#gid=1430583426',
    rValue: 200000000,
    commission: 0.1,
    team: '마케팅2팀',
    pl: '최경영',
    submittedAt: '2025-01-01',
    year: 2025,
    status: 'FIRST_PAID',
    incentiveRate: 2,
    incentiveFund: 400000,
    firstPaymentDate: '2025-05-09',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '2025. 06 이후 대행 일시중단으로 보임 250509 1차 지급 완료',
    members: [
      { memberId: 'm6', memberName: '최경영', contribution: 90 },
      { memberId: 'unknown', memberName: '이윤희', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00014',
    campaignName: '와디즈',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1ggvtfs4wfQhSSJHgoPDQmdLCxlnclId3bx2xVhnnmIs/edit?gid=779608449#gid=779608449',
    rValue: 1200000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '김익현',
    submittedAt: '2025-01-01',
    year: 2025,
    status: 'ALL_PAID',
    incentiveRate: 2,
    incentiveFund: 2400000,
    firstPaymentDate: '2025-08-08',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2026-02-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: true,
    slackNotified: true,
    note: '2026. 02. 10 2차 수주인센티브 지급 계약기간 2025. 12. 31 까지 250709 8/10 1차(60%) 지급 3/12 ~ 실집행 시작, 6개월 집행된 시점에 절반 이상 소진하면 60% 지급, 캠페인 종료 후 40% 지급',
    members: [],
  },
  {
    id: 'PROPJ00015',
    campaignName: '그라비티(냥농장타이쿤)',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1HNpHfTTU7q-Y5hC7YjFZ1qUtjYFCZ9VCZvQQ0_ExoDw/edit?usp=drive_link',
    rValue: 56000000,
    commission: 0.1,
    team: '마케팅2팀',
    pl: '박경빈',
    submittedAt: '2025-01-01',
    year: 2025,
    status: 'ALL_PAID',
    incentiveRate: 2,
    incentiveFund: 112000,
    firstPaymentDate: '2025-04-10',
    firstPaymentRatio: 1,
    secondPaymentRatio: 0,
    secondPaymentDate: '2025-04-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: true,
    slackNotified: true,
    note: '250410 일괄지급 완료',
    members: [
      { memberId: 'unknown', memberName: '박경빈', contribution: 40 },
      { memberId: 'm45', memberName: '박민규', contribution: 40 },
      { memberId: 'm44', memberName: '김남솔', contribution: 20 }
    ],
  },
  {
    id: 'PROPJ00016',
    campaignName: '롯데카드-띵샵',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1T_oVFUlD99mO3GKc0w02BRpV5G79aYrxWli6F7cx3hY/edit?usp=drivesdk',
    rValue: 2000000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '',
    submittedAt: '2025-07-17',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 4000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: false,
    members: [],
  },
  {
    id: 'PROPJ00017',
    campaignName: '현대카드',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1ZIrFIYcKE9WOGnSso9kRVDgtV4gO3yrow8Npn8wm2gA/edit?usp=drivesdk',
    rValue: 8000000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '최다솜',
    submittedAt: '2025-11-03',
    year: 2025,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 16000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00018',
    campaignName: 'DB손해보험 TM',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1C6LZOXIL0Ft_VQMu22qt1DgB1YPo6rlpRssJWWhgAA8/edit?usp=drivesdk',
    rValue: 7000000000,
    commission: 0.15,
    team: '마케팅5팀',
    pl: '김영현',
    submittedAt: '2025-11-07',
    year: 2025,
    status: 'SECOND_PENDING',
    incentiveRate: 2,
    incentiveFund: 21000000,
    firstPaymentDate: '2025-12-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2027-02-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '251210 1차 지급 완료',
    members: [
      { memberId: 'm16', memberName: '김영현', contribution: 60 },
      { memberId: 'm26', memberName: '정유진', contribution: 25 },
      { memberId: 'm56', memberName: '김민국', contribution: 5 },
      { memberId: 'unknown', memberName: 'Creative.Lab', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00019',
    campaignName: 'DB손해보험_자동차',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1VoGU0Pvb-uuTjg640hfsEBiJ5ns3axn5IoFftZddsDE/edit?usp=drivesdk',
    rValue: 3000000000,
    commission: 0.15,
    team: '마케팅2팀',
    pl: '최경영',
    submittedAt: '2025-11-10',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 9000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00020',
    campaignName: '전북은행',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1VGm7pFkCckA1ZNjhOJYVVkq_OKo9hCBsY5yROD8ky08/edit?usp=drivesdk',
    rValue: 4500000000,
    commission: 0.1,
    team: '마케팅2팀',
    pl: '최경영',
    submittedAt: '2025-11-07',
    year: 2025,
    status: 'SECOND_PENDING',
    incentiveRate: 2,
    incentiveFund: 9000000,
    firstPaymentDate: '2026-01-09',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2027-02-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '260109 1차 지급 완료',
    members: [
      { memberId: 'm6', memberName: '최경영', contribution: 38 },
      { memberId: 'm32', memberName: '정지성', contribution: 32 },
      { memberId: 'unknown', memberName: '김규리', contribution: 9 },
      { memberId: 'm48', memberName: '정수아', contribution: 7 },
      { memberId: 'm45', memberName: '박민규', contribution: 4 },
      { memberId: 'm47', memberName: '이용희', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00021',
    campaignName: '아정당',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1ok8WUHG4QvVd6VozDAtIGXXlvNnjbSLdgGRXKAwnx44/edit?usp=drivesdk',
    rValue: 8000000000,
    commission: 0.1,
    team: '마케팅1팀',
    pl: '신희도',
    submittedAt: '2025-11-07',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 16000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00022',
    campaignName: '잡코리아_알바몬',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1gP3Mzf_0sKTkGpA7nEltQkegBGFwQMNlr2rkr9nF5Mw/edit?usp=drivesdk',
    rValue: 7000000000,
    commission: 0.1,
    team: '마케팅1팀',
    pl: '정소미',
    submittedAt: '2025-11-05',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 14000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00023',
    campaignName: '펍지_Balenciaga',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1vDGIXsa299_Nl8SpC87-sP3iPgzkmEmVAvErsHVSXHs/edit?usp=drivesdk',
    rValue: 700000000,
    commission: 0.1,
    team: '마케팅3팀',
    pl: '김도경',
    submittedAt: '2025-11-03',
    year: 2025,
    status: 'ALL_PAID',
    incentiveRate: 2,
    incentiveFund: 1400000,
    firstPaymentDate: '2026-01-09',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2026-02-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: true,
    slackNotified: true,
    note: '260210 2차 지급 예정 260109 1차 지급 완료',
    members: [
      { memberId: 'm21', memberName: '박승혁', contribution: 30 },
      { memberId: 'm61', memberName: '전다예', contribution: 30 },
      { memberId: 'm44', memberName: '김남솔', contribution: 20 },
      { memberId: 'm50', memberName: '이창환', contribution: 20 },
      { memberId: 'm51', memberName: '정성은', contribution: 1 }
    ],
  },
  {
    id: 'PROPJ00024',
    campaignName: '아워홈',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1yOMnPCcwRx1LpqlWVgD21mVxyI270IIYC81wmzWtrxM/edit?usp=drivesdk',
    rValue: 2000000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '김익현',
    submittedAt: '2025-11-25',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 4000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00025',
    campaignName: 'NH투자증권',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1Y17hwizdulnqJv7dLgBFfvy_qi4EBG1phnXoubuzMyk/edit?usp=drivesdk',
    rValue: 9750000000,
    commission: 0.13,
    team: '마케팅1팀',
    pl: '정소미',
    submittedAt: '2025-12-18',
    year: 2025,
    status: 'SECOND_PENDING',
    incentiveRate: 2,
    incentiveFund: 25350000,
    firstPaymentDate: '2026-02-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: '2027-02-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '260210 1차 지급 완료',
    members: [
      { memberId: 'unknown', memberName: '정소미', contribution: 15 },
      { memberId: 'unknown', memberName: '송두리', contribution: 30 },
      { memberId: 'm10', memberName: '박화진', contribution: 20 },
      { memberId: 'm20', memberName: '조원형', contribution: 20 },
      { memberId: 'unknown', memberName: '정민혁', contribution: 5 },
      { memberId: 'unknown', memberName: 'Creative.Lab', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00026',
    campaignName: 'DB생명보험',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1nfickSmne6Oe5sZdPldSnde1id5IMhOV7BfhJmcUq98/edit?usp=drivesdk',
    rValue: 5000000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '류승일',
    submittedAt: '2025-11-28',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 10000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: false,
    members: [],
  },
  {
    id: 'PROPJ00027',
    campaignName: '크리에이블',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1z4GiPVXR_wcBE0Y2B6sMyV5DLkYihOfyAQL1yN9ZbRY/edit?usp=drivesdk',
    rValue: 360000000,
    commission: 0.15,
    team: '마케팅1팀',
    pl: '',
    submittedAt: '2025-01-01',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 1080000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: false,
    members: [],
  },
  {
    id: 'PROPJ00028',
    campaignName: '모두의연구소',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1ab_2PFFi_wiGNou7l0rzObSE0pxhI8N50Me2n7Ebsbs/edit?usp=drivesdk',
    rValue: 1000000000,
    commission: 0.15,
    team: '마케팅6팀',
    pl: '정대욱',
    submittedAt: '2025-12-12',
    year: 2025,
    status: 'FIRST_PAID',
    incentiveRate: 2,
    incentiveFund: 3000000,
    firstPaymentDate: '2026-02-10',
    firstPaymentRatio: 30,
    secondPaymentRatio: 70,
    secondPaymentDate: undefined,
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '260210 1차 지급 완료',
    members: [
      { memberId: 'm70', memberName: '정대욱', contribution: 60 },
      { memberId: 'm72', memberName: '김보현', contribution: 20 },
      { memberId: 'm52', memberName: '김세형', contribution: 10 },
      { memberId: 'm73', memberName: '김민지', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00029',
    campaignName: '자비스엔빌런즈',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1vjlJlJyrgtcD0E-nhTWyeOl0bJjRJVyDs6aepnFTMVw/edit?usp=drivesdk',
    rValue: 2300000000,
    commission: 0.1,
    team: '마케팅2팀',
    pl: '최다솜',
    submittedAt: '2025-12-30',
    year: 2025,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 4600000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00030',
    campaignName: '삼성카드',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/12zsysiUi7dxNqFiWpGhYtbmD2V0PLF2xj3G-Wbg3Qiw/edit?usp=drivesdk',
    rValue: 7000000000,
    commission: 0.1,
    team: '마케팅2팀',
    pl: '김익현',
    submittedAt: '2026-01-02',
    year: 2026,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 14000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00031',
    campaignName: '쥬비스',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/14_rhHbII3arnPcbxIKFmhoxIbdIB4RCHg_nAAPATkDk/edit?usp=drivesdk',
    rValue: 5000000000,
    commission: 0.1,
    team: '마케팅6팀',
    pl: '정대욱',
    submittedAt: '2025-12-22',
    year: 2025,
    status: 'FIRST_PAID',
    incentiveRate: 2,
    incentiveFund: 10000000,
    firstPaymentDate: '2026-02-13',
    firstPaymentRatio: 30,
    secondPaymentRatio: 70,
    secondPaymentDate: undefined,
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '260309 쥬비스 운영 종료 (Drop 최종결정, 2차 지급 X) 260210 1차 지급 하는 것으로 결정 → 2/13 지급예정 260130 드롭가능성 있어 지급 홀딩',
    members: [
      { memberId: 'm70', memberName: '정대욱', contribution: 40 },
      { memberId: 'm72', memberName: '김보현', contribution: 40 },
      { memberId: 'm73', memberName: '김민지', contribution: 20 }
    ],
  },
  {
    id: 'PROPJ00032',
    campaignName: '네오위즈_고양이와스프',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/14lyiyevAx6vuuBYK1VdAb91ObyAk_1oBQZklJxGA9_Y/edit?usp=drivesdk',
    rValue: 5100000000,
    commission: 0.1,
    team: '마케팅3팀',
    pl: '정성은',
    submittedAt: '2026-01-30',
    year: 2026,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 10200000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00033',
    campaignName: '풀리오',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1YFze20C7oErZ-czH-H4aYXZV5WLQ1uAGJbuhReGRYfA/edit?usp=drivesdk',
    rValue: 5000000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '왕선영',
    submittedAt: '2026-01-30',
    year: 2026,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 10000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00034',
    campaignName: '오케이저축은행/캐피탈',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1dr4ydpExBx6jAU9XU3u_fa4EVQkxcHiSAehftcHAWhE/edit?usp=drivesdk',
    rValue: 6400000000,
    commission: 0.1,
    team: '마케팅6팀',
    pl: '정대욱',
    submittedAt: '2026-01-16',
    year: 2026,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 12800000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00035',
    campaignName: 'IBK카드',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1eIomnRuQZieYtRy1uogecNRKSgrT70Bk0fqL1T2ncuM/edit?usp=drivesdk',
    rValue: 988931000,
    commission: 0.1495,
    team: '마케팅2팀',
    pl: '최다솜',
    submittedAt: '2026-01-22',
    year: 2026,
    status: 'FIRST_PAID',
    incentiveRate: 2,
    incentiveFund: 2956904,
    firstPaymentDate: '2026-03-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '260310 1차 지급 완료',
    members: [
      { memberId: 'unknown', memberName: '최다솜', contribution: 20 },
      { memberId: 'm31', memberName: '김정태', contribution: 20 },
      { memberId: 'm25', memberName: '이채영', contribution: 20 },
      { memberId: 'unknown', memberName: '이시은', contribution: 20 },
      { memberId: 'm67', memberName: '김상욱', contribution: 20 }
    ],
  },
  {
    id: 'PROPJ00036',
    campaignName: '유니세프_2026',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1nYOI4Lzn6roWiMLTkZnZF2yzjE3tpwy0c_Xgql4WMRM/edit?usp=drivesdk',
    rValue: 5000000000,
    commission: 0.1,
    team: '마케팅6팀',
    pl: '정대욱',
    submittedAt: '2026-02-20',
    year: 2026,
    status: 'FIRST_PENDING',
    incentiveRate: 2,
    incentiveFund: 10000000,
    firstPaymentDate: '2026-04-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '운영 경과 1년 시점 2차 지급 예정 (2027. 04. 10 예정) 260410 1차 지급 완료',
    members: [
      { memberId: 'm70', memberName: '정대욱', contribution: 70 },
      { memberId: 'm62', memberName: '김아원', contribution: 10 },
      { memberId: 'm72', memberName: '김보현', contribution: 10 },
      { memberId: 'unknown', memberName: 'Creative.Lab', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00037',
    campaignName: '웰컴저축은행',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1U4dfImMJmu2u2GyDAQiDD5L6q-Q3d1UWg5Iet4kCFRc/edit?usp=drivesdk',
    rValue: 3000000000,
    commission: 0.025,
    team: '마케팅6팀',
    pl: '정대욱',
    submittedAt: '2026-01-29',
    year: 2026,
    status: 'FIRST_PAID',
    incentiveRate: 2,
    incentiveFund: 1500000,
    firstPaymentDate: '2026-03-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '260310 1차 지급 완료',
    members: [
      { memberId: 'm70', memberName: '정대욱', contribution: 50 },
      { memberId: 'm47', memberName: '이용희', contribution: 50 }
    ],
  },
  {
    id: 'PROPJ00038',
    campaignName: '카카오게임즈_프로젝트 OQ',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1rzfHj11FataogJI1_nhtM2rqdHEYMHpk3FRvBrd22X8/edit?usp=drivesdk',
    rValue: 10000000000,
    commission: 0.09,
    team: '마케팅3팀',
    pl: '정성은',
    submittedAt: '2026-03-03',
    year: 2026,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 18000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00039',
    campaignName: '남양유업',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/19dXGKi5ci3iPCR1oJuNu-1gCgoPQcFu4hgcqtYiyoIE/edit?usp=drivesdk',
    rValue: 2200000000,
    commission: 0.15,
    team: '마케팅6팀',
    pl: '김보현',
    submittedAt: '2026-02-25',
    year: 2026,
    status: 'FIRST_PAID',
    incentiveRate: 2,
    incentiveFund: 6600000,
    firstPaymentDate: '2026-04-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    note: '260410 1차 지급 완료',
    members: [
      { memberId: 'm72', memberName: '김보현', contribution: 50 },
      { memberId: 'm70', memberName: '정대욱', contribution: 10 },
      { memberId: 'm47', memberName: '이용희', contribution: 10 },
      { memberId: 'm62', memberName: '김아원', contribution: 10 },
      { memberId: 'm52', memberName: '김세형', contribution: 10 },
      { memberId: 'unknown', memberName: '팀 전체', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00040',
    campaignName: '아식스코리아_오니즈카 타이거에',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/11VqsRT8te8hAJ1xysy0WdzsW7hyDLTMgxL0varVhOEE/edit?usp=drivesdk',
    rValue: 500000000,
    commission: 0.15,
    team: '마케팅6팀',
    pl: '정대욱',
    submittedAt: '2026-02-25',
    year: 2026,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 1500000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00041',
    campaignName: 'PUBG 9주년 캠페인(3월)',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1yJsh621xkQC1B-gl1_eoLu_mhQvZJm5m65ZZauZ0Apw/edit?usp=drivesdk',
    rValue: 250000000,
    commission: 0.1,
    team: '마케팅3팀',
    pl: '정성은',
    submittedAt: '2026-02-23',
    year: 2026,
    status: 'ALL_PAID',
    incentiveRate: 2,
    incentiveFund: 500000,
    firstPaymentDate: '2026-04-10',
    firstPaymentRatio: 1,
    secondPaymentRatio: 0,
    secondPaymentDate: '2026-04-10',
    firstPaymentCompleted: true,
    secondPaymentCompleted: true,
    slackNotified: true,
    members: [
      { memberId: 'm51', memberName: '정성은', contribution: 35 },
      { memberId: 'm61', memberName: '전다예', contribution: 65 }
    ],
  },
  {
    id: 'PROPJ00042',
    campaignName: '비비안_샌디즈',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/15zTXgDvJPcWdNm54c3vb7bJYFBzwBQTpKYCN_rXRZlg/edit?usp=drivesdk',
    rValue: 1200000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '왕선영',
    submittedAt: '2026-02-20',
    year: 2026,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 2400000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00043',
    campaignName: '전기아이피(위메이드 계열사)_미르의전설2, 미르의전설3',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1xeTJSZN0zLVB6oImK277ulmzsLekg8sVDvLP7kES2j0/edit?usp=drivesdk',
    rValue: 130000000,
    commission: 0.15,
    team: '마케팅3팀',
    pl: '정성은',
    submittedAt: '2026-02-25',
    year: 2026,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 390000,
    firstPaymentDate: '2026-06-10',
    firstPaymentRatio: 1,
    secondPaymentRatio: 0,
    secondPaymentDate: '2026-06-10',
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [
      { memberId: 'm51', memberName: '정성은', contribution: 90 },
      { memberId: 'm61', memberName: '전다예', contribution: 10 }
    ],
  },
  {
    id: 'PROPJ00044',
    campaignName: 'KT알파',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1Z-XFz5sNEQNiaqaO1YSfZP_XqAvtKiZhgZvEzlAcQPY/edit?usp=drivesdk',
    rValue: 5800000000,
    commission: 0.07,
    team: '마케팅2팀',
    pl: '김익현',
    submittedAt: '2026-03-17',
    year: 2026,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 8120000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00045',
    campaignName: '게임듀오_신작 모바일 게임',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1EtRIIX2dOW967L1qoxkXi4n9NT1ZomFD-UnFvkpfiMY/edit?usp=drivesdk',
    rValue: 500000000,
    commission: 0.1,
    team: '마케팅3팀',
    pl: '정성은',
    submittedAt: '2026-04-03',
    year: 2026,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 1000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00046',
    campaignName: '아이소이',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/16pwnqaaH9e_PAO0CvHgiTNElY8yV_kYF8ru3hcyKJrY/edit?usp=drivesdk',
    rValue: 3000000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '왕선영',
    submittedAt: '2026-04-03',
    year: 2026,
    status: 'PL_COMPLETED',
    incentiveRate: 2,
    incentiveFund: 6000000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00047',
    campaignName: '데싱디바_브랜딩',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1wCkqjoC8TCwylhFeI8Ye4_rvNeDOcsAfKkTEtoiC6Do/edit?usp=drivesdk',
    rValue: 1025000000,
    commission: 0.13,
    team: '마케팅2팀',
    pl: '류승일',
    submittedAt: '2026-04-06',
    year: 2026,
    status: 'FIRST_PENDING',
    incentiveRate: 2,
    incentiveFund: 2665000,
    firstPaymentDate: '2026-05-08',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00048',
    campaignName: '그린피스_2026',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1uGS220NHTLSsXp3ACNKFKaUFVysMXlLkFvQQl6wJTZI/edit?usp=drivesdk',
    rValue: 1000000000,
    commission: 0.14,
    team: '마케팅4팀',
    pl: '왕선영',
    submittedAt: '2026-03-23',
    year: 2026,
    status: 'FIRST_PAID',
    incentiveRate: 2,
    incentiveFund: 2800000,
    firstPaymentDate: '2026-05-08',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00049',
    campaignName: 'KB핀테크(KB알다)',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1Q5XI_eCJBPjuTvViR9tW5BYsP9b9V5DI_yEpJBxdhEY/edit?usp=drivesdk',
    rValue: 1200000000,
    commission: 0.1,
    team: '마케팅4팀',
    pl: '김보미',
    submittedAt: '2026-04-14',
    year: 2026,
    status: 'FIRST_PAID',
    incentiveRate: 2,
    incentiveFund: 2400000,
    firstPaymentDate: '2026-05-08',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: true,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00050',
    campaignName: 'NENURI',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1lPOcnXV6f5ABopTZWJ2mJjiwgtoQ_ySL3WJ0ZSn4qow/edit?usp=drivesdk',
    rValue: 250000000,
    commission: 0.15,
    team: '마케팅3팀',
    pl: '정성은',
    submittedAt: '2026-04-24',
    year: 2026,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 750000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00051',
    campaignName: '그래픽',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/18xjkvC69O5ZlvHk4VZr3fs9jErYgRc0wFLB9WPkUZFs/edit?usp=drivesdk',
    rValue: 200000000,
    commission: 0.15,
    team: '마케팅3팀',
    pl: '정성은',
    submittedAt: '2026-04-21',
    year: 2026,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 600000,
    firstPaymentDate: '2026-07-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00052',
    campaignName: '아이덴티티게임즈_드래곤네스트:월드',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1SllFGQkrgGRyJr6HHHlOBOdBjGsgSseRPNbq-0zohug/edit?usp=drivesdk',
    rValue: 200000000,
    commission: 0.1,
    team: '마케팅3팀',
    pl: '정성은',
    submittedAt: '2026-04-24',
    year: 2026,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 400000,
    firstPaymentDate: undefined,
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
  {
    id: 'PROPJ00053',
    campaignName: '패스트뷰_차살때',
    committeeSheetLink: 'https://docs.google.com/spreadsheets/d/1j9sYQ61ABU1PlUsQSj6PTHtA6TR7AsX1JHzLcUTt1PU/edit?usp=drivesdk',
    rValue: 2160000000,
    commission: 0.12,
    team: '마케팅6팀',
    pl: '정대욱',
    submittedAt: '2025-01-01',
    year: 2025,
    status: 'PL_PENDING',
    incentiveRate: 2,
    incentiveFund: 5184000,
    firstPaymentDate: '2026-06-10',
    firstPaymentRatio: 60,
    secondPaymentRatio: 40,
    secondPaymentDate: undefined,
    firstPaymentCompleted: false,
    secondPaymentCompleted: false,
    slackNotified: true,
    members: [],
  },
];